### ISSUE TITLE
VirusTotal report

### ISSUE THREAD

**Issue by saracenaly** [MustafaKrc/ITU-CRN-Picker#3]
Virustotal labels your executable as malecious,  check out here:

https://www.virustotal.com/gui/file/b0627b8fd8106567cc28a2636856197885d5bce6802e5f4b69f6ff889c7cbe5b?nocache=1

**Comment by MustafaKrc** [comment]
Thank you for your feedback. Unfortunately, this project is no longer actively maintained. We have moved our efforts to a more comprehensive solution called BeeHub, which covers similar functionality and more. You can find all updates and the latest features on our new platform at [BeeHub](https://www.beehubapp.com/).
