### ISSUE TITLE
Request limit update

### ISSUE THREAD

**Issue by SchumacherFarad** [MustafaKrc/ITU-CRN-Picker#4]
https://github.com/MustafaKrc/ITU-CRN-Picker/blob/1668e83ac0368f3db154b7b65005343eef8be79d/ui/qml/pages/SettingsPage.qml#L94C21-L94C25

As announced today, the Kepler site will limit us all to one request per 3 seconds. You can update the line above as 3.1, or 3 as request will also take an amount of time.

![image](https://github.com/user-attachments/assets/8cebabee-0f9f-42e8-9dcc-6398fcb7e641)

**Comment by MustafaKrc** [comment]
Thank you for your feedback. Unfortunately, this project is no longer actively maintained. We have moved our efforts to a more comprehensive solution called BeeHub, which covers similar functionality and more. You can find all updates and the latest features on our new platform at [BeeHub](https://www.beehubapp.com/).

**Comment by MustafaKrc** [comment]
Thank you for your feedback. Unfortunately, this project is no longer actively maintained. We have moved our efforts to a more comprehensive solution called BeeHub, which covers similar functionality and more. You can find all updates and the latest features on our new platform at [BeeHub](https://www.beehubapp.com/).
